In [7]:
pip --version

pip 25.3 from C:\Users\shraw\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip (python 3.14)

Note: you may need to restart the kernel to use updated packages.


In [10]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 1.5 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.8 MB 1.5 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.8 MB 1.5 MB/s eta 0:00:01
   ----------------- ---------------------- 0.8/1.8 MB 772.7 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 880.1 kB/s eta 0:00:01
   ---------------------------- ----------- 1.3/1.8 MB 892.3 kB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 887.2 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 925.7 kB/s  0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Note: you may need to restart the kernel to use updated packages.


In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

print(np.__version__)

2.5.3


In [3]:
a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(a.ndim)   # Number of dimensions
print(a.shape)   # Size of each dimension
print(a.size)    # Total number of elements

3
(2, 2, 2)
8


Create a 1D NumPy array containing 10 numbers. Display the array and find its ndim, shape, and size.

Create a 1D NumPy array containing the values 5, 10, 15, 20, 25, 30. Find the sum, mean, maximum, and minimum of the array.Create two 1D NumPy arrays:

 Create a 1D NumPy array containing 2, 4, 6, 8, 10. Find the square of each element and display the result


Create two 1D NumPy arrays:

A = [10, 20, 30, 40, 50]

B = [2, 4, 5, 8, 10]

Perform addition, subtraction, multiplication, and division between the two arrays.


 Create a 2D NumPy array with 3 rows and 4 columns. Display the array and find its ndim, shape, and size.


Create the following 2D NumPy array:

[[10, 20, 30],

 [40, 50, 60],

 [70, 80, 90]]

Find the sum, mean, maximum, and minimum of all elements.

Create a 2D NumPy array containing the values:

[[2, 4, 6],

 [8, 10, 12],

 [14, 16, 18]]

Find the square and cube of every element.


Create a 3D NumPy array containing 24 elements. Display its ndim, shape, and size.


Create the following 3D NumPy array:

[

    [[1, 2, 3], [4, 5, 6]],

    [[7, 8, 9], [10, 11, 12]]

]

Find the sum, mean, maximum, and minimum of all elements.


Create a 3D NumPy array with 2 blocks, 3 rows, and 4 columns. Display the array and find its ndim, shape, size, sum, mean, maximum, and minimum.

In [13]:
#Create a 1D NumPy array containing 10 numbers. Display the array and find its ndim, shape, and size.
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
10


In [22]:
#Create a 1D NumPy array containing the values 5, 10, 15, 20, 25, 30. \
#Find the sum, mean, maximum, and minimum of the array.Create two 1D NumPy arrays:
import numpy as np

a = np.array([5, 10, 15, 20, 25, 30])
b = np.array([2, 5, 63, 42, 2, 5])

print("sum:", np.sum(a))
print("mean:", np.mean(a))
print("Max", np.max(a))
print("minimum:", np.min(a))

sum: 105
mean: 17.5
Max 30
minimum: 5


In [26]:
#Create a 1D NumPy array containing 2, 4, 6, 8, 10. Find the square of each element and display the result
import numpy as np

a = np.array([2, 4, 6, 8, 10])

print("Square: ", np.sqrt(a))

Square:  [1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [30]:
'''
Create two 1D NumPy arrays:

A = [10, 20, 30, 40, 50]

B = [2, 4, 5, 8, 10]

Perform addition, subtraction, multiplication, and division between the two arrays.
'''
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])

print("Add:", (a + b))
print("Sub:", (a - b))
print("Mult:", (a * b))
print("Div:", (a / b))

Add: [12 24 35 48 60]
Sub: [ 8 16 25 32 40]
Mult: [ 20  80 150 320 500]
Div: [5. 5. 6. 5. 5.]


In [43]:
#Create a 2D NumPy array with 3 rows and 4 columns. Display the array and find its ndim, shape, and size.
import numpy as np

a = np.array([
    [2, 2, 3, 4],
    [5, 8, 6, 4],
    [7, 5, 6, 2],
])

print(a.shape)
print(a.ndim)
print(a.size)

(3, 4)
2
12


In [53]:
'''
Create the following 2D NumPy array:

[[10, 20, 30],

[40, 50, 60],

[70, 80, 90]]

Find the sum, mean, maximum, and minimum of all elements.
'''
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Dimentation:", a.ndim)
print(a)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

Dimentation: 2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
450
50.0
90
10


In [66]:
'''
Create a 2D NumPy array containing the values:

[[2, 4, 6],

[8, 10, 12],

[14, 16, 18]]

Find the square and cube of every element.
'''
import numpy as np

a = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

print(a.ndim)
print(a**2)
print(a**3)

2
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]
[[   8   64  216]
 [ 512 1000 1728]
 [2744 4096 5832]]


In [68]:
#Create a 3D NumPy array containing 24 elements. Display its ndim, shape, and size.

import numpy as np

a = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(a.ndim)
print(a.size)
print(a.shape)

3
24
(2, 3, 4)


In [70]:
'''
Create the following 3D NumPy array:

[

[[1, 2, 3], [4, 5, 6]],

[[7, 8, 9], [10, 11, 12]]
]

Find the sum, mean, maximum, and minimum of all elements.

'''
import numpy as np

a = np.array([
    [

    [1, 2, 3], [4, 5, 6],

    [7, 8, 9], [10, 11, 12]
    ]
])

print(a.ndim)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

3


In [77]:
'''
Create a 3D NumPy array with 2 blocks, 3 rows, and 4 columns. Display the array \
and find its ndim, shape, size, sum, mean, maximum, and minimum.
'''
import numpy as np

a = np.array ([
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]
    ],
    [
        [1, 2, 3, 33],
        [1, 2, 3, 4],
        [1, 2, 3, 4] 
    ]
])

print('shape:',a.shape)
print("Dimension:", a.ndim)
print("Size:", a.size)
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("maximum:", np.max(a))
print("manimum:", np.min(a))

shape: (2, 3, 4)
Dimension: 3
Size: 24
Sum: 89
Mean: 3.7083333333333335
maximum: 33
manimum: 1
